AWSTemplateFormatVersion: '2010-09-09'
Description: 'Auxiliary sidecar resources for ppc-ecommerce-payment-service'

Resources:
  PaymentTransactionsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub 'ppc-ecommerce-payment-txns-${AWS::Region}'
      AttributeDefinitions:
        - AttributeName: transactionId
          AttributeType: S
      KeySchema:
        - AttributeName: transactionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
